esphome:
  name: "${name}"
  friendly_name: "${NAME}"
  comment: "LILYGO LoRa32 (ttgo-lora32-v21)"
  libraries:
    - rtl_433_ESP=https://github.com/NorthernMan54/rtl_433_ESP.git#v0.3.2
    - RadioLib@6.1.0
  includes:
    - 433/rtl433-to-mqtt.h
  platformio_options:
    lib_ldf_mode: "chain+"
    build_flags:
      #- '-DLOG_LEVEL=LOG_VERBOSE'
      - '-DONBOARD_LED=LED_BUILTIN'
      #- '-DPUBLISH_UNPARSED=true'
      #- '-DRAW_SIGNAL_DEBUG'
      #- '-DRTL_VERBOSE=63'
      #- '-DMY_DEVICES'
      #- '-DREGOOKFIX_DEBUG'
      #- '-DRF_MODULE_INIT_STATUS'
      - '-DRF_SX1278'
      - '-DRF_MODULE_FREQUENCY=433.92'

esp32:
  board: ttgo-lora32-v21
  framework:
    type:  arduino
    version: recommended
    platform_version: 6.1.0

custom_component:
  - id: rtl433
    lambda: return { new Rtl433ToMqtt("${name}") };

interval:
  - interval: 60s
    then:
      - lambda: Rtl433ToMqtt::get(id(rtl433))->status();

ota:
  on_begin:
    - lambda: Rtl433ToMqtt::get(id(rtl433))->stop();
